config/routes.rb
TrakkorRails3::Application.routes.draw do
  get "trackers/update"
  get "trackers/find_xpath"
  get "trackers/test_xpath"
  resources 'trackers' do
  end

  match "/stats" => 'trackers#stats'

  root :to => 'trackers#index'

  require Rails.root.join("lib/status_app")
  mount StatusApp => "/_status"

end

app/models/piece.rb
class Piece < ActiveRecord::Base
  belongs_to :tracker

  attr_accessor :error

  def fetch(uri,xpath)
    text, error = Piece.fetch_text(uri, xpath)

    self.text = text
    self.error = error

    self
  end

  def Piece.extract_with_parents(doc, xpath)
    piece = e = doc.at(xpath)
    parents = []
    while e.parent.class != Nokogiri::HTML::Document do
      parents << e.parent
      e = e.parent
    end
    [piece,parents[0..2]]
  end

  def Piece.fetch_title(uri)
    text, _ = Piece.fetch_text(uri, '//title/text()')
    return text
  end

  def before_save
    self.text = Piece.tidy_text(self.text) if self.text
  end

  def same_content(other)
    !other.nil? && other.text == self.text
  end

  def Piece.tidy_text(str)
    str = tidy_tabby_lines(str)
    str = tidy_multiple_nl(str)
    str.strip[0,1_000]
  end

  private
  def self.fetch_text(uri, xpath)
    service_url = "http://getxpath.better-idea.org/get"
    service_params = {url: uri, xpath: xpath}

    begin
      response = Piece.fetch_from_uri(service_url, service_params)
    rescue => e
      error = "Error: #{e.to_s}"
      return ["", error]
    end

    if response.success?
      response_json = JSON.parse(response.body)
      text = response_json.fetch("result")
      error = response_json.fetch("error")
      return [text, error]
    elsif response.code.to_i == 0
      error = "Error: #{response.code} #{response.options.fetch(:return_code)}"
      return ["", error]
    else
      error = "Error #{response.code}"
      return ["", error]
    end
  end

  def Piece.fetch_from_uri(uri_str, params)
    Typhoeus::Request.get(uri_str, followlocation: true, connecttimeout: 2_000, maxredirs:4, timeout: 10_000,  params: params)
  end

  def Piece.tidy_tabby_lines(str)
    str.gsub(/\n\t+\n/, "\n\n")
  end

  def Piece.tidy_multiple_nl(str)
    str.gsub(/\n\n+/, "\n")
  end
end

app/models/tracker.rb
require 'json'

class Tracker < ActiveRecord::Base
  R_URI = /^(http|https):\/\/.*?$/ix

  attr_accessible :uri, :xpath, :name, :web_hook

  validates_presence_of :uri, :xpath
  validates_format_of :uri, :with =>  R_URI
  validates_format_of :web_hook, :with =>  R_URI, :allow_blank => true
  validates_uniqueness_of :code

  before_create :generate_code
  before_create :set_name

  after_create :push_a_piece

  has_many :pieces, :order => 'created_at DESC', :dependent => :destroy

  def to_param
    "#{code}"
  end

  def generate_code
    self.code = SecureRandom.hex(6)
  end

  def validate_on_create
    @first_piece = fetch_piece
    if @first_piece.error
      errors.add("URI and XPath", "yield no content")
    end
  end

  def set_name
    if self.name.blank?
      description = (html_title.presence || uri).truncate(50)
      self.name = "Tracker for '#{description}'"
    end
  end

  def before_update
    set_name
  end

  def Tracker.uri?(str)
    str =~ R_URI
  end

  def push_a_piece
    fetch_piece.save!
  end

  def current_piece
    pieces.first
  end

  def last_modified
    last_anything = current_piece
    if last_anything
      last_anything.updated_at.utc
    else
      Time.now.utc
    end
  end

  def html_title
    Piece.fetch_title(self.uri)
  end

  def fetch_piece
    p = Piece.new.fetch(uri, xpath)
    p.tracker = self
    p
  end

  def sick?
    self.error_count > 10
  end

  def pieces_count
    self.pieces.count
  end

  def self.fetch_doc_from(uri)
    unless Tracker.uri?(uri)
      err = "Please provide a proper HTTP URI like http://w3c.org"
      return nil, err
    end

    response= Piece.fetch_from_uri(uri, {})
    unless response.success?
      err =  "Could not fetch the document, " +
        "server returned: #{response.code} #{response.body}"
      return nil, err
    end

    doc = Nokogiri::HTML(response.body)
    unless doc
      err = 'URI does not point to a document that Trakkor understands.'
      return nil, err
    end

    return doc, nil
  end

  def Tracker.find_nodes_by_text(doc, str)
    nodes = []
    doc.traverse { |node|
      if(node.inner_text =~ /#{str}/i)
        nodes << node
      end
    }

    nodes
  end

  def Tracker.live_examples
    Tracker.find_all_by_id(APP_CONFIG['example_trackers'] || [])
  end

  private
  def Tracker.collect_parents(n, parents)
    return if n.class == Hpricot::Doc

    if n.parent
      parents << n.parent
      collect_parents(n.parent, parents)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController

  def index
    trackers = Tracker.live_examples

    last_modified = trackers.map{ |t| t.last_modified }.max
    fresh_when(:last_modified => last_modified, :public => true)

    @trackers = trackers
  end

  def show
    @tracker = Tracker.find_by_code(params[:id])

    unless @tracker
      render :text => 'No tracker found for this id.', :status => 404
      return
    end

    if stale?(:last_modified => @tracker.last_modified, :public => true)
      @changes = @tracker.pieces

      respond_to do |format|
        format.html
        format.atom
        format.json { render json: {tracker: @tracker, pieces: @changes} }
      end
    end
  end

  def new
    @tracker = Tracker.new(params[:tracker])

    if @tracker.uri && @tracker.xpath
      @tracker.set_name
    end
  end

  def find_xpath
    @hits = flash[:error] = nil
    @uri  = params[:uri]
    @q    = params[:q]

    if @uri.blank? || @q.blank?
      flash[:error] = "Please provide an URI and a search term."
      return
    end

    doc, err = Tracker.fetch_doc_from(@uri)
    if doc
      @hits =  Tracker.find_nodes_by_text(doc, @q)
    else
      flash[:error] = err
    end
  end

  def test_xpath
    @uri = params[:uri]
    @xpath = params[:xpath]

    if @uri.blank? || @xpath.blank?
      flash[:error] = "Please provide an URI and an XPath."
      return
    end

    doc, err = Tracker.fetch_doc_from(@uri)
    if doc
      @elem, @parents = Piece.extract_with_parents(doc, @xpath)
    else
      flash[:error] = err
    end
  end

  def stats
    authenticate
    @trackers = Tracker.all
  end

  def update
    TrackerUpdater.new(Rails.logger).update_trackers
    render text: "Ok"
  end

  def create
    @tracker = Tracker.new(params[:tracker])

    if @tracker.save
      flash[:notice] = 'Tracker was successfully created.'

      redirect_path = tracker_path(id: @tracker.code)
      redirect_to redirect_path
    else
      render :action => "new"
    end
  end

  private
  def authenticate
    authenticate_or_request_with_http_basic("Trakkor admin") do |username, password|
      username == "admin" && password == APP_CONFIG['password']
    end
  end
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
 def html_title(str="")
    unless str.blank?
      content_for :html_title do
       "&mdash; #{h str}".html_safe
      end
    end
  end  

end

app/helpers/trackers_helper.rb
module TrackersHelper

  def timeago(time, options = {})
    options[:class] ||= "timeago"
    if time
      utc_timestamp = time.utc.iso8601
      content_tag(:abbr, utc_timestamp, options.merge(:title => utc_timestamp))
    end
  end

  def htidy(text)
    h(Piece.tidy_text(text))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrakkorRails3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/trackers.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <% if (html_title = yield :html_title) %>
    <title>Trakkor <%= html_title %></title>
  <% else %>
    <title>Trakkor</title>
  <% end %>
  <%= stylesheet_link_tag 'trakkor' %>
  <%= stylesheet_link_tag 'base' %>
  <%= stylesheet_link_tag 'themes/blue/style' %>

  <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js' %>
  <%= javascript_include_tag 'jquery.timeago.js' %>

  <link rel="shortcut icon" href="<%= image_path('favicon.ico') %>" />

  <% if @tracker %>
  <link rel="alternate" type="application/atom+xml" href="<%= "#{url_for(@tracker)}.atom" %>" />
  <% end %>

</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Trakkor</a></h1>

      <div id="main-navigation">
        <ul>
          <li class="first active"><a href="/">Introduction</a></li>
          <li><a href="/#faq">FAQ</a></li>
        </ul>
        <div class="clear"></div>
      </div>
    </div>
    <div id="wrapper">
      <div id="main">

        <div class="block" id="block-text">
          <div class="content">
            <div class="inner">

                <%= yield  %>

            </div>
          </div>
        </div>

        <div id="footer">
          <div class="block">
            <p><a href='<%= root_path %>'>Trakkor</a>, tracking your changes since May 2008.
                Running on <a href='http://rubyonrails.org'>Rails</a>.
                Created by <a href='http://www.better-idea.org'>Matthias Lüdtke</a>.</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('abbr[class*=timeago]').timeago();
    });
  </script>

</body>
</html>

app/views/trackers/_find_xpath_form.erb
<%= form_tag trackers_find_xpath_path, :method => :get, :class => 'form' do -%>

<div class="group">
  <label class="label">URL</label>
  <%= text_field_tag 'uri', uri, :size => 80, :class => 'text_field' %>
</div>

<div class="group">
  <label class="label">Find text</label>
  <%= text_field_tag 'q', q, :size => 80, :class => 'text_field' %>
</div>

<div class="group navform">
  <%= submit_tag 'Test and track' %>
</div>
<% end -%>

app/views/trackers/_piece.erb
<tr>
    <td class='piece'><pre><%= htidy piece.text %></pre></td>
</tr>

<tr>
  <td class='change_datetime'>
    <%= timeago(piece.created_at) %>
  </td>
</tr>

app/views/trackers/_proceed_with_hit.erb
<a href='<%= url_for(:action => 'test_xpath', :uri => @uri, :xpath => hit.path)  %>'>Proceed</a>

<span>with <%= h(hit.path) %></span>

<pre class='piece'>
<%=  htidy(hit.inner_text).gsub(/(#{Regexp.escape(@q)})/i, ("<strong class='highlightsearch'>\\1</strong>")).html_safe %>
</pre>

app/views/trackers/_tracker_for_hit.erb
<a href='<%=  url_for(:action => 'new', :tracker => {:uri => @uri, :xpath => hit.path})  %>'>Create tracker</a>

<span>for <%= hit.path %></span>

<pre>
<%= htidy(hit.inner_text) %>
</pre>

app/views/trackers/create.html.erb
<h1>Trackers#create</h1>
<p>Find me in app/views/trackers/create.html.erb</p>

app/views/trackers/destroy.html.erb
<h1>Trackers#destroy</h1>
<p>Find me in app/views/trackers/destroy.html.erb</p>

app/views/trackers/find_xpath.html.erb
<h2>Step 1: Find piece by text</h2>

<p>Enter the location of the HTML document and (part of) the text you want to track.</p>

<%= render :partial => 'find_xpath_form',
           :locals => { :q => @q, :uri => @uri } %>

<% if flash[:error] %>
<div class="flash">
  <div class="message error">
    <p><%= flash[:error] %></p>
  </div>
</div>
<% else %>


<%= error_messages_for :tracker %>



<% if @hits && !@hits.empty? %>
<div class="flash">
  <div class="message notice">
    <p><%= pluralize(@hits.size, "element") %> found.</p>
  </div>
</div>

<ol class='hitlist'>

<%- @hits = @hits.sort_by{|h| h.inner_text.length}%>

<% for hit in @hits %>
 <li>
  <%= render :partial => "proceed_with_hit", :locals => { :hit => hit } %>
 </li>
<% end %>

</ol>

<% else %>
<div class="flash">
  <div class="message error">
    <p>No elements have been found matching <i><%= @q %></i></p>
  </div>
</div>
<% end %>

<% end # if flash['error'] %>

app/views/trackers/index.html.erb
<% html_title("Web page change tracking") -%>

<h2>What is it?</h2>
<p>Change tracking of single web page elements and notification via Atom feed, that is what Trakkor provides. Completely free.</p>
<p>Monitoring complete web pages is easy. But have you ever wanted to track just a single
piece of information from a web page, like a product price or the headline of your
favorite news site which does not provide an RSS feed?
</p>

<p>
Trakkor lets you create a tracker for just a single DOM element given
by an XPath and informs you via Atom feed if it changes.
</p>

<%= error_messages_for :tracker %>

<%
 example_uri ='http://example.com'
 example_search = 'example'
-%>


<h2>Try tracking</h2>
<p>Enter a web page address and the text you want to track.</p>
<%= render :partial => 'find_xpath_form', 
           :locals => { :q => example_search, :uri => example_uri } %>

<h2>Live examples</h2>

<table class='examples'>
<% for tracker in @trackers %>
  <tr>
    <td><a href="<%= "#{url_for(tracker)}.atom" %>"><%= image_tag("feed-icon-tiny.png", :alt => "Tracker Feed for #{tracker.uri}") %></a></td>
    <td><%= link_to "#{tracker.name}", tracker_path(tracker) %>
      <br/><span class='change_time'><%= timeago(tracker.last_modified) %></span>
    </td>
    <td class='piece'><%= htidy tracker.current_piece.text %></td>
  </tr>
<% end %>
</table>

<br />

<h2>What is it not?</h2>
<p>
Trakkor is just a change tracker for single web page elements which happens to present its findings via Atom feeds. That is what it's good at.
</p>

<p>But Trakkor is not good at recognizing the structure of the HTML pieces it scrapes out of a document. That's why it treats those pieces as raw strings: If one character changes, it differs for Trakkor.</p>

<p>And Trakkor is probably not the tool you should use if you want to create Atom feeds for web sites which don't publish an Atom feed but perhaps better should.</p>

<p>It's really just a very simple change tracker, believe me. Just try it out and see if it suits you.</p>

<h2>Web Hooks</h2>
<p>Web Hooks provide a simple hook mechanism for the Web. By using HTTP POST and a serialization format like JSON a web service may inform another via its Web Hook. You can find more information on the <a href='http://webhooks.pbworks.com/'>Web Hooks Wiki</a>.
</p>

<p>
Trakkor allows you to define a Web Hook for your tracker that will be triggered on every change. Your custom Web Hook may send you an email or Jabber message or log the changes to a custom log file format, whatever you implement.
</p>

<h2 id='faq'>FAQ</h2>
<div class='listblock'>
 <ul>

 <li class='q'>How often is a web page checked for changes?</li>
 <li class='a'>Currently each page is checked every 30 minutes.</li>

 <li class='q'>How many changes do you save per tracker?</li>
 <li class='a'>Every change which is detected gets saved. But to keep our database tidy each tracker's changes are kept only for 6 months.</li>

<li class='q'>Are the any tools that might help me find a fitting XPath if Trakkor doesn't cut it?</li>
<li class='a'>Finding an appropriate XPath that selects the desired element can be difficult: I suggest using either the <a href="https://addons.mozilla.org/en-US/firefox/addon/1192/" title='XPather Firefox addon'>XPather</a> or <a href="https://addons.mozilla.org/en-US/firefox/addon/1095/" title='XPath Checker Firefox addon'>XPath Checker</a> Firefox addons. Both allow you to right-click a page element and give you an XPath that describes it. But please bear in mind that some of the XPathes created by these tools (e.g. the id() function) are not understood by Trakkor's Hpricot library, see <a href='http://wiki.github.com/hpricot/hpricot/supported-xpath-expressions' title='XPath expressions supported by Trakkor'>Supported XPath Expressions</a> for details.</li>

 </ul>
</div> <!-- listblock !-->

<h2 id='thanks'>Thanks</h2>
<p>Trakkor uses several fine pieces of software which made development fun. I'd like to thank</p>
<div class='listblock'>
<ul>
  <li>Andrea Franz for his <a href='http://github.com/pilu/web-app-theme'>Web App Theme</a></li>
  <li>Logoinstant for their <a href='http://www.logoinstant.com/2008/12/good-waves/'>Good Waves icon</a></li>
  <li>why the lucky stiff for <a href='http://wiki.github.com/hpricot/hpricot/'>Hpricot</a></li>
  <li>Ryan McGeary for the <a href='http://timeago.yarp.com/'>jQuery timeago plugin</a></li>
  <li>Ryan Tomayko for <a href='http://rtomayko.github.com/rack-cache/'>Rack::Cache</a></li>
  <li>Wikimedia's user Jahoe <a title="By Feed-icon.svg: unnamed (Mozilla Foundation) derivative work: User:Jahoe [GPL (http://www.gnu.org/licenses/gpl.html), LGPL (http://www.gnu.org/licenses/lgpl.html), GPL (http://www.gnu.org/licenses/gpl.html) or LGPL (http://www.gnu.org/licenses/lgpl.html)], via Wikimedia Commons" href="http://commons.wikimedia.org/wiki/File%3AGeneric_Feed-icon.svg">for the feed icon</a></li>
</ul>
</div> <!-- listblock !-->

app/views/trackers/new.html.erb
<h2>Step 3: Create the tracker</h2>

<%= error_messages_for :tracker %>

<%= form_for @tracker, :url => {:action => "create"}, :html => {:class => 'form'}  do |f| -%>

<div class="group">
  <label class="label">URL</label>
  <%= f.text_field 'uri', :size => 80, :class => 'text_field' %>
</div>

<div class="group">
  <label class="label">XPath</label>
  <%= f.text_field 'xpath', :size => 80, :class => 'text_field' %>
</div>

<div class="group">
  <label class="label">Name</label>
  <%= f.text_field 'name', :size => 80, :class => 'text_field' %>
</div>

<div class="group">
  <label class="label">Web Hook URL</label>
  <%= f.text_field 'web_hook', :size => 80, :class => 'text_field' %>
</div>

<div class="group navform">
 <%= f.submit 'Create' %>
</div>

<% end -%>

app/views/trackers/show.html.erb
<% html_title(@tracker.name) -%>


<h2 id='tracker_title'><%= @tracker.name %></h2>
<p id='created_on'>created <%= @tracker.created_at.strftime('%d %b %Y') %></p>

<p>
This tracker monitors the document at <br />
  <a id='uri_for_tracker' href='<%= h @tracker.uri %>'><%= h @tracker.uri %></a> <br/>
for changes to the element given by the XPath <br />
  <span id='xpath_for_tracker'><%= @tracker.xpath %></span>
</p>

<% if @tracker.sick? %>
  <div class="flash" id="sick_tracker_message">
    <div class="message warning">
      <p>This tracker may be sick, Trakkor failed to retrieve recent pieces.
      </p>
    </div>
  </div>
<% end %>

<% if @tracker.web_hook.present? %>
  <p class='web_hook'>
    The Web Hook at
      <span id='web_hook_for_tracker'><%= h @tracker.web_hook %></span>
    gets notified on every change.
  </p>
<% end %>

<h2 id='changes'><%= link_to 'Changes', "#{url_for(@tracker)}.atom" %></h2>

<table id='changetable'>
  <%= render partial: "piece", collection: @changes %>
</table>

app/views/trackers/stats.html.erb
<p>
Trakkor is currently running <%= Tracker.count %> trackers,
comprising <%= Piece.count %> number of pieces.
</p>

<h3>Trackers (<%= ( @trackers || []).length %>)</h3>
<table>
  <tr>
    <th>Errors</th>
    <th>Name</th>
    <th>Id</th>
    <th>Sick</th>
    <th>#Pieces</th>
    <th>Last Err</th>
    <th>Hook</th>
  </tr>
  <% for t in @trackers %>
    <tr>
    <td>  <%= t.error_count > 0 ? t.error_count : '' %> </td>
    <td> <%= link_to(t.name.truncate(50), t) %></td>
    <td><%= t.id %></td>
    <td>  <%= t.sick? ? 'sick' : '' %> </td>
    <td><%= t.pieces_count %></td>
    <td><%= t.last_error %></td>
    <td>  <%= t.web_hook %> </td>
  </tr>
<% end %>
</table>

app/views/trackers/test_xpath.html.erb
<h2>Optional Step 2: Try a parent element</h2>

<%= error_messages_for :tracker %>


<%= form_tag( {:controller => 'trackers', :action => 'test_xpath'}, :method => :get, :class => 'form' ) do -%>


<div class="group">
  <label class="label">URL</label>
  <%= text_field_tag 'uri', @uri, :size => 80, :class => 'text_field' %>
</div>


<div class="group">
  <label class="label">Find text</label>
  <%= text_field_tag 'xpath', @xpath, :size => 80, :class => 'text_field' %>
</div>

<div class="group navform">
 <%= submit_tag 'Refresh preview' %>
</div>

<% end -%>


<%- if @elem %>
<h2>Exact piece</h2>
<%= render :partial => "tracker_for_hit", :locals => { :hit => @elem } %>

<h2>Some parent pieces</h2>
<ol class='hitlist'>
<% for p in @parents %>
 <li>
  <%= render :partial => "tracker_for_hit", :locals => { :hit => p } %>
 </li>
<% end %>

</ol>

<% end -%>